### PR TITLE
Hello o/ - Update this awesome plugin to work with our 1.8 servers.

### PR DESCRIPTION
**Pull request by FabioZumbi12**
Hey, since i openned my server i use this plugin!! Now, i learned java and i have coded some plugins. Since 1.8 i having little issues with this plugin, and i decided to colabore to this project and update/improve to new versions!

If you like, accept this pull and add me to managers on bukkit to i post new changed .jar. Or you can do this.

Thanks and great job!

### CODE REVIEW

**Comment by Bathlamos** [comment]
Hi there Fabio!

Thank you for lending us a hand to improve the LetItRain plugin. It really needed an update. I'll just test your changes in the next day and I will make you admin on Bukkit and on this repository afterward.

**Comment by ashtreylil** [comment]
can you do a 1.7.9 cb version also?

**Comment by Bathlamos** [comment]
@FabioZumbi12 @Maty241 Can one of you create that version?

@FabioZumbi12 Still waiting for your Bukkit Dev username :)

**Comment by FabioZumbi12** [comment]
Oh, sorry! Its the same, FabioZumbi12! I think already is 1.7.9 compatible but if not, i can make!

**Comment by Bathlamos** [comment]
Cool! You're now a Bukkit Dev LetItRain maintainer :)
Feel free to upload your most recent builds, and be sure to tell me if your permissions are not high enough!

**Pull request merged**
